# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfV81cQfOBJA1AOpnHahw41zoybTfFqB
"""

import streamlit as st
from keras.models import load_model  # Sekarang aman menggunakan ini
from PIL import Image, ImageOps
import numpy as np

# --- Konfigurasi Halaman ---
st.set_page_config(page_title="Klasifikasi Sawit", page_icon="🌴")

# --- Judul ---
st.title("🌴 Deteksi Kematangan Kelapa Sawit")
st.write("Unggah gambar: **Unripe (Mentah)**, **Ripe (Matang)**, atau **Overripe (Lewat Matang)**.")

# --- Fungsi Load Model ---
@st.cache_resource
def load_prediction_model():
    # compile=False penting agar tidak error saat load optimizer
    model = load_model("keras_model.h5", compile=False)
    return model

try:
    model = load_prediction_model()
except Exception as e:
    st.error(f"Error: {e}. Pastikan file 'keras_model.h5' ada di folder ini.")

# --- Label Kelas ---
# Sesuaikan urutan ini dengan Teachable Machine Anda
class_names = ["Unripe (Mentah)", "Ripe (Matang)", "Overripe (Lewat Matang)"]

# --- Upload Gambar ---
file_upload = st.file_uploader("Upload gambar sawit...", type=["jpg", "png", "jpeg"])

if file_upload is not None:
    image = Image.open(file_upload).convert("RGB")
    st.image(image, caption="Gambar Upload", use_column_width=True)

    # --- Proses Gambar ---
    size = (224, 224)
    image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
    image_array = np.asarray(image)

    # Normalisasi (Standard Teachable Machine)
    normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1

    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    data[0] = normalized_image_array

    # --- Prediksi ---
    if model:
        prediction = model.predict(data)
        index = np.argmax(prediction)
        class_name = class_names[index]
        confidence = prediction[0][index]

        st.success(f"Hasil: **{class_name}**")
        st.info(f"Akurasi: {confidence * 100:.2f}%")
        st.progress(int(confidence * 100))